services:
  - type: web
    name: playwright-automation-platform
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService: true
    healthCheckPath: /health
    autoDeploy: true
    branch: main
    rootDir: .
    scaling:
      minInstances: 1
      maxInstances: 1