services:
  - type: web
    name: playwright-automation-platform
    env: node
    plan: free
    buildCommand: "npm install && npm run build && cd backend && npm install"
    startCommand: "node backend/server.js"
    healthCheckPath: /health
    autoDeploy: true
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
    routes:
      - type: rewrite
        source: /api/*
        destination: /api/*
      - type: rewrite
        source: /*
        destination: /index.html